#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-picocli
Version  : 2.3.0
Release  : 1
URL      : https://github.com/remkop/picocli/archive/v2.3.0.tar.gz
Source0  : https://github.com/remkop/picocli/archive/v2.3.0.tar.gz
Source1  : https://repo1.maven.org/maven2/info/picocli/picocli/2.3.0/picocli-2.3.0.jar
Source2  : https://repo1.maven.org/maven2/info/picocli/picocli/2.3.0/picocli-2.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-picocli-data = %{version}-%{release}
Requires: mvn-picocli-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
[![GitHub Release](https://img.shields.io/github/release/remkop/picocli.svg)](https://github.com/remkop/picocli/releases)
[![Build Status](https://travis-ci.org/remkop/picocli.svg?branch=master)](https://travis-ci.org/remkop/picocli)
[![codecov](https://codecov.io/gh/remkop/picocli/branch/master/graph/badge.svg)](https://codecov.io/gh/remkop/picocli)
[![Follow @remkopopma](https://img.shields.io/twitter/follow/remkopopma.svg?style=social)](https://twitter.com/intent/follow?screen_name=remkopopma)
[![Follow @picocli](https://img.shields.io/twitter/follow/picocli.svg?style=social)](https://twitter.com/intent/follow?screen_name=picocli)

%package data
Summary: data components for the mvn-picocli package.
Group: Data

%description data
data components for the mvn-picocli package.


%package license
Summary: license components for the mvn-picocli package.
Group: Default

%description license
license components for the mvn-picocli package.


%prep
%setup -q -n picocli-2.3.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-picocli
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-picocli/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/info/picocli/picocli/2.3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/info/picocli/picocli/2.3.0/picocli-2.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/info/picocli/picocli/2.3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/info/picocli/picocli/2.3.0/picocli-2.3.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/info/picocli/picocli/2.3.0/picocli-2.3.0.jar
/usr/share/java/.m2/repository/info/picocli/picocli/2.3.0/picocli-2.3.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-picocli/LICENSE
